### ISSUE TITLE
Problem with the add_pose topic. Wrong subscriber

### ISSUE THREAD

**Issue by supertoto29** [sonia-auv/sonia-ros-bridge#15]
**Warning :** Before creating an issue or task, make sure that it does not already exists in the [issue tracker](../). Thank you.

## Expected Behavior
The type of the message should be a sonia_common/add_pose

## Current Behavior
The type of the message is geometry_msg. The only subscriber is the rosbridge_websocket as shown in the screenshot. Proc_control was not started and was not able to start.

## Comments
![Screenshot from 2022-05-31 18-21-48](https://user-images.githubusercontent.com/44241055/171294009-9ebb9acc-97e6-4ca9-a1c4-19cf06f64d04.png)

## Environment Used
- Project version : 1.1.6

**Comment by alexemdesgagne** [comment]
I found the issue in the telemetry. This is corrected.
