### ISSUE TITLE
Migrate to ROS noetic

### ISSUE THREAD

**Issue by alexemdesgagne** [sonia-auv/sonia-ros-bridge#7]
## Expected Enhancement
Migrate this node to use ROS noetic.

**Comment by Kam0ss** [comment]
I don't think there is anything to do because of this line in the DockerFile : 
`RUN apt-get update && apt-get install -y ros-${ROS_DISTRO}-rosbridge-server`

**Comment by alexemdesgagne** [comment]
Just update the package to rebuild with the latest sonia_common version and making sure it's working properly.
